#ifndef COLOR_H
#define COLOR_H
#include<windows.h>

typedef enum _FgColor {
  FG_BLACK = 0,
  FG_DARK_BLUE = FOREGROUND_BLUE,
  FG_DARK_GREEN = FOREGROUND_GREEN,
  FG_DARK_CYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,
  FG_DARKRED = FOREGROUND_RED,
  FG_DARK_MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
  FG_DARK_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
  FG_DARK_GRAY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
  FG_GRAY = FOREGROUND_INTENSITY,
  FG_BLUE = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
  FG_GREEN = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
  FG_CYAN = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
  FG_RED = FOREGROUND_INTENSITY | FOREGROUND_RED,
  FG_MAGENTA = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
  FG_YELLOW = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
  FG_WHITE = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
} FgColor;

typedef enum _BgColor {
  BG_BLACK = 0,
  BG_DARK_BLUE = BACKGROUND_BLUE,
  BG_DARK_GREEN = BACKGROUND_GREEN,
  BG_DARK_CYAN = BACKGROUND_GREEN | BACKGROUND_BLUE,
  BG_DARKRED = BACKGROUND_RED,
  BG_DARK_MAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
  BG_DARK_YELLOW = BACKGROUND_RED | BACKGROUND_GREEN,
  BG_DARK_GRAY = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
  BG_GRAY = BACKGROUND_INTENSITY,
  BG_BLUE = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
  BG_GREEN = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
  BG_CYAN = BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE,
  BG_RED = BACKGROUND_INTENSITY | BACKGROUND_RED,
  BG_MAGENTA = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE,
  BG_YELLOW = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
  BG_WHITE = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
} BgColor;

#endif
